### ISSUE TITLE
Allow values from url to be used in shortcode.

### ISSUE THREAD

**Issue by chelminski** [alicolville/shortcode-variables#58]
# Short description of the request

Allow values from url to be used in shortcode. Specifically, I mean the database shortcode. (sc-db-value-by-id)

# What is it about?

Many pages in my WordPress display content dynamically, you can see many things at one URL depending on the query parametr. 

So, for example, 

I can see the accounts of different users at the URL address.

`https://example.com/user-details?user=chelminski`

`https://example.com/user-details?user=test`

I would like to be able to use a given value from the url, such as `user | id | ip` etc. directly in this shortcode.

# Example 1

`https://example.com/user-details?user=chelminski`
`[sv slug="sc-db-value-by-url-key" table="users_data" column="user_ip" column-to-search="user" url-key="user" key-format="%s"]`

Select `user_ip` from `users_data` where `user` = `chelminski`
Return value: 192.168.0.69
# Example 2

`https://example.com/order-details?id=2137&status=packed&green_path=1`
`[sv slug="sc-db-value-by-url-key" table="orders" column="currency" column-to-search="id" url-key="id" key-format="%d"]`

Select `currency` from `orders` where `id` = `2137`
Return value: USD

I would like to ask you to implement the new function, it would be very helpful to me :D!

**Comment by chelminski** [comment]
# Similar plugin
(Maybe this will be helpful anyway)
https://pl.wordpress.org/plugins/url-params/

**Comment by alicolville** [comment]
I'm so sorry, for some reason never saw the notification on this!!

Is this something you're still interested in? It is something I could potentially add :)

**Comment by chelminski** [comment]
Hi :D !
I'm so glad you're back online. Yes, that feature would still be very helpful.I would be extremely grateful if this was implemented, it would solve a lot of problems on my site.

**Comment by alicolville** [comment]
I'll see what I can do

**Comment by alicolville** [comment]
Next release (going our shortly) will have the following:

[sv slug="sc-db-value-by-id" table="wp_users" column="user_login" column-to-search="id" **key-query-string**="user-id" key-format="%d"]
