### ISSUE TITLE
Add user phone number

### ISSUE THREAD

**Issue by sbservices** [alicolville/shortcode-variables#61]
Hi, just posting a request here to see if user phone number could be added to shortcodes please.

**Comment by alicolville** [comment]
I'm afraid phone number isn't a standard WP field, a plugin must be adding that? Therefore it maybe more complicated. Do you know which plugin is adding it?

**Comment by sbservices** [comment]
It is woocommerce. I have written some custom code in to functions.php to pull through the phone number based on selected user.  I think the field was billing_phone.

**Comment by sbservices** [comment]
might be handy enough. I only had 1 client needing it, perhaps she would find it handy when looking up a member that hasn't turned up and wanted to phone them after class or something. But I wouldn't put yourself to any trouble if no-one else needing it.

**Comment by alicolville** [comment]
The following will exist in the next release: 

```
[sv slug="sc-woocommerce" field="billing_first_name"]
[sv slug="sc-woocommerce" field="billing_last_name"]
[sv slug="sc-woocommerce" field="billing_company"]
[sv slug="sc-woocommerce" field="billing_address_1"]
[sv slug="sc-woocommerce" field="billing_address_2"]
[sv slug="sc-woocommerce" field="billing_city"]
[sv slug="sc-woocommerce" field="billing_postcode"]
[sv slug="sc-woocommerce" field="billing_country"]
[sv slug="sc-woocommerce" field="billing_state"]
[sv slug="sc-woocommerce" field="billing_email"]
[sv slug="sc-woocommerce" field="billing_phone"]
[sv slug="sc-woocommerce" field="shipping_first_name"]
[sv slug="sc-woocommerce" field="shipping_last_name"]
[sv slug="sc-woocommerce" field="shipping_company"]
[sv slug="sc-woocommerce" field="shipping_address_1"]
[sv slug="sc-woocommerce" field="shipping_address_2"]
[sv slug="sc-woocommerce" field="shipping_city"]
[sv slug="sc-woocommerce" field="shipping_postcode"]
[sv slug="sc-woocommerce" field="shipping_country"]
[sv slug="sc-woocommerce" field="shipping_state"]
```

**Comment by alicolville** [comment]
Deployed. Read more: https://snippet-shortcodes.yeken.uk/shortcodes/sc-woocommerce.html

**Comment by sbservices** [comment]
cool! Thanks Ali, that's awesome.
